//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSES3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSESEntities : DbContext
    {
        public SSESEntities()
            : base("name=SSESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Door> Doors { get; set; }
        public virtual DbSet<DoorsCredential> DoorsCredentials { get; set; }
        public virtual DbSet<DoorsDeatail> DoorsDeatails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersCredential> UsersCredentials { get; set; }
    }
}
